# Generated by Django 6.0.3 on 2026-05-04 03:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_extensions'),
        ('plans', '0002_plan_search_vector_plan_idx_plan_search_vector'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_task_search_vector'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comment',
            trigger=pgtrigger.compiler.Trigger(name='comment_fanout_to_task_search_vector', sql=pgtrigger.compiler.UpsertTriggerSql(func="UPDATE tasks_task t SET search_vector = \n    setweight(to_tsvector('english_unaccent', coalesce(t.title, '')), 'A') ||\n    setweight(to_tsvector('english_unaccent', coalesce(t.description, '')), 'B') ||\n    setweight(to_tsvector('english_unaccent',\n        coalesce((\n            SELECT string_agg(c.body, ' ')\n            FROM tasks_comment c\n            WHERE c.task_id = t.id\n        ), '')\n    ), 'C')\n WHERE t.id = COALESCE(NEW.task_id, OLD.task_id); RETURN NULL;", hash='42befc2db3308aa13b6ba8986f81f7a3037ac3dc', operation='INSERT OR UPDATE OF "body", "task_id" OR DELETE', pgid='pgtrigger_comment_fanout_to_task_search_vector_4feee', table='tasks_comment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='task_search_vector_self', sql=pgtrigger.compiler.UpsertTriggerSql(func="NEW.search_vector := \n    setweight(to_tsvector('english_unaccent', coalesce(NEW.title, '')), 'A') ||\n    setweight(to_tsvector('english_unaccent', coalesce(NEW.description, '')), 'B') ||\n    setweight(to_tsvector('english_unaccent',\n        coalesce((\n            SELECT string_agg(c.body, ' ')\n            FROM tasks_comment c\n            WHERE c.task_id = NEW.id\n        ), '')\n    ), 'C')\n; RETURN NEW;", hash='3f69ec8044bb2808aa23d6e8a7e89cc782ee2eba', operation='INSERT OR UPDATE OF "title", "description"', pgid='pgtrigger_task_search_vector_self_c182b', table='tasks_task', when='BEFORE')),
        ),
    ]
