# Generated by Django 6.0.3 on 2026-05-04 03:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_extensions'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title', config='english_unaccent', weight='A'), '||', django.contrib.postgres.search.SearchVector('description', config='english_unaccent', weight='B'), django.contrib.postgres.search.SearchConfig('english_unaccent')), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_plan_search_vector'),
        ),
    ]
